CREATE TABLE IF NOT EXISTS safe_hashes(
  id INTEGER PRIMARY KEY,
  `hash` TEXT NOT NULL,
  `path` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS malware_hashes(
  id INTEGER PRIMARY KEY,
  `hash` TEXT NOT NULL,
  confidence INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS report_cache(
  id INTEGER PRIMARY KEY,
  `hash` TEXT NOT NULL,
  report TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scan_history(
  id INTEGER PRIMARY KEY,
  `date` TEXT NOT NULL,
  files INTEGER DEFAULT 0,
  threats INTEGER DEFAULT 0,
  `type` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS threat_history(
  id INTEGER PRIMARY KEY,
  `type` TEXT NOT NULL,
  severity INTEGER DEFAULT 0,
  `description` TEXT NOT NULL
);